@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 11 16:49:33 +0200 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim in_first_wz_behav -key {Behavioral:sim_1:Functional:in_first_wz} -tclbatch in_first_wz.tcl -view D:/Proggetti Reti Logiche/10619348_RL_proj/project_tb_behav.wcfg -log simulate.log"
call xsim  in_first_wz_behav -key {Behavioral:sim_1:Functional:in_first_wz} -tclbatch in_first_wz.tcl -view D:/Proggetti Reti Logiche/10619348_RL_proj/project_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
